name: BUILD

on:
  workflow_dispatch:
  
jobs:
  Build-x86-64:
    uses: cjsas/OpenWrt-Build/.github/workflows/build-openwrt.yml@main
    with:
      target: x86-64
  Build-r2s:
    uses: cjsas/OpenWrt-Build/.github/workflows/build-openwrt.yml@main
    with:
      target: r2s
  Build-rpi-4:
    uses: cjsas/OpenWrt-Build/.github/workflows/build-openwrt.yml@main
    with:
      target: rpi-4
